# Generated by Django 4.2.5 on 2024-01-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VEndpoints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmlrequest',
            name='full_response',
            field=models.FileField(blank=True, null=True, upload_to='results/', verbose_name='结果'),
        ),
    ]
