# Generated by Django 4.2.5 on 2024-01-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VEndpoints', '0002_alter_vmlrequest_full_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmlrequest',
            name='full_response',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='结果'),
        ),
    ]
