# Generated by Django 4.2.5 on 2024-01-21 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chunked_upload', '0005_alter_chunkedupload_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyChunkedUpload',
            fields=[
                ('chunkedupload_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chunked_upload.chunkedupload')),
            ],
            options={
                'abstract': False,
            },
            bases=('chunked_upload.chunkedupload',),
        ),
    ]
