# Generated by Django 4.2.5 on 2024-01-31 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VEndpoints', '0004_alter_vmlrequest_response'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vmlalgorithm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VEndpoints.vmlalgorithm'),
        ),
    ]
