# Generated by Django 4.2.5 on 2024-02-16 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VEndpoints', '0004_alter_vmlrequest_response'),
        ('video', '0002_alter_video_vmlalgorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='vmlres',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VEndpoints.vmlrequest'),
        ),
    ]
